ot_core_homepage:
    path:     /
    defaults: { _controller: OTCoreBundle:Home:index }

ot_core_viewAll_characs:
      path:    charac/view_all
      defaults: { _controller: OTCoreBundle:Charac:viewAll }

ot_core_view_charac:
      path:    charac/view/{id}
      defaults:  
          _controller: OTCoreBundle:Charac:view
      requirements:
          id:    \d+

ot_core_add_charac:
      path:    charac/add
      defaults: { _controller: OTCoreBundle:Charac:add }

ot_core_delete_charac:
      path:    charac/delete/{id}
      defaults:  
          _controller: OTCoreBundle:Charac:delete
      requirements:
          id:    \d+

ot_core_edit_charac:
      path:    charac/edit/{id}
      defaults:  
          _controller: OTCoreBundle:Charac:edit
      requirements:
          id:    \d+
