<?php

namespace OT\CoreBundle\Repository;

/**
 * CharacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacRepository extends \Doctrine\ORM\EntityRepository
{
}
